### PR TITLE
Fix force image set

### PR DESCRIPTION
**Pull request by homeworkprod**
See commit message for details.

### CODE REVIEW

**Comment by homeworkprod** [comment]
@SasaKaranovic would you mind taking a look at this? It fixes an issue I've encountered.

**Comment by SasaKaranovic** [comment]
Hey @homeworkprod 
Sorry about that.

How are you using this parameter? Maybe updating the documentation is more appropriate.

Reason I'm suggesting this is that this parameter should "almost never" be used.
It is a fail-safe to force the server to update the dials image, even if it's certain that the dial already contains the exact same image and therefore no update is required.

So in normal operation you would completely omit this parameter. And if you need to use it, you would just set it, the value is ignored.

Also in the future, opening an issue first is probably better way to do this.
I should add a contribution guide so we can guide people better in the future.

**Comment by homeworkprod** [comment]
Ok, so you're saying the query parameter is supposed to have an effect when it is set, regardless of its value? Then indeed making that clear in the docs would've helped me.

> How are you using this parameter?

It's been two months and I can't remember why I wanted to, and did, use it, but I guess I had *some* reason. I'll let you know once I remember it or encounter such a situation again. No need to investigate this further right know, I think.

> Also in the future, opening an issue first is probably better way to do this.

Fair point. I try to reduce noise/overhead a bit by often going straight to a PR, but this does have drawbacks.

**Comment by SasaKaranovic** [comment]
That is correct. Just setting the parameter is sufficient.
And this parameter should not be used under "normal operation", so I will document it better.

> Fair point. I try to reduce noise/overhead a bit by often going straight to a PR, but this does have drawbacks.

Just to clarify, it takes time and effort to make a PR! With that said I really appreciate all the help that people want to offer!
The "issue first, PR later" approach helps avoid wasted work and also allows everyone to get aligned before any work is kicked off.

**Pull request closed without merging**
